using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BE
{
    public class BE_Orden_Servicio
    {

		public int ID { get; set; }
		public string ID_CLIENTE { get; set; }
		public string TIPO_DOC { get; set; }
		public string NUM_DOC { get; set; }
		public string RAZON_SOCIAL { get; set; }
		public string NUM_ORDEN_SERVICIO { get; set; }
		public string FLAG_TRANSPORTE { get; set; }
		public string FLAG_CUADRILLA { get; set; }
		public string FLAG_RESGUARDO { get; set; }
		public string FLAG_AGE_ADUANA { get; set; }
		public string FLAG_AGE_CARGA { get; set; }
		public string FLAG_OTROS { get; set; }
		public string TRA_NUM_GR_REMITENTE { get; set; }
		public string TRA_NUM_GR_TRANSPORTE { get; set; }
		public string TRA_PLACA { get; set; }
		public string TRA_BREVETE { get; set; }
		public string TRA_DIRECCION_INICIO { get; set; }
		public string TRA_DIRECCION_LLEGADA { get; set; }
		public string TRA_TIPO_CARGA { get; set; }
		public string TRA_NUM_CONTENEDOR { get; set; }
		public string TRA_PESO { get; set; }
		public string TRA_FECHA_SERVICIO { get; set; }
		public string TRA_TIPO_BULTO { get; set; }
		public string TRA_NUM_BULTO { get; set; }
		public string CUAD_SERVICIO { get; set; }
		public string CUAD_DETALLE { get; set; }
		public string CUAD_LUGAR { get; set; }
		public string CUAD_NUM_PERSONAS { get; set; }
		public string RESG_PROVEEDOR { get; set; }
		public string RESG_RUTA { get; set; }
		public string AGE_ADU_ADUANA { get; set; }
		public string AGE_ADU_MANIFIESTO { get; set; }
		public string AGE_ADU_REGIMEN { get; set; }
		public string AGE_ADU_DAM { get; set; }
		public string AGE_ADU_CANAL { get; set; }
		public string AGE_ADU_EMPRESA { get; set; }
		public string AGE_ADU_FEC_ARRIBO { get; set; }
		public string AGE_ADU_FEC_RETIRO { get; set; }
		public string AGE_ADU_ALMACEN { get; set; }
		public string AGE_ADU_VALORFOB { get; set; }
		public string AGE_ADU_VALORCIF { get; set; }
		public string AGE_CAR_ADUANA { get; set; }
		public string AGE_CAR_MANIFIESTO { get; set; }
		public string AGE_CAR_PUERTO_ORIGEN { get; set; }
		public string AGE_CAR_PAIS { get; set; }
		public string AGE_CAR_EMP_TRANSP { get; set; }
		public string AGE_CAR_EMPRESA { get; set; }
		public string AGE_CAR_FEC_ARRIBO { get; set; }
		public string AGE_CAR_FEC_RETIRO { get; set; }
		public string AGE_CAR_PESO { get; set; }
		public string AGE_CAR_VOLUMEN { get; set; }
		public string AGE_CAR_NUM_BULTO { get; set; }
		public string AGE_CAR_ALMACEN { get; set; }
		public string OTRO_DETALLE { get; set; }
		public string OTRO_OBSERVACION { get; set; }
		public string ESTADO { get; set; }
		public string FECHA_CREACION { get; set; }
		public string FECHA_MODIFICACION { get; set; }
		public string USUARIO_CREACION { get; set; }
		public string USUARIO_MODIFICACION { get; set; }
		public string TIPO_SERVICIO { get; set; }

		public string ARCHIVO1_NOMBRE_ORIGINAL { get; set; }
		public string ARCHIVO1_NOMBRE_GENERADO { get; set; }
		public string ARCHIVO1_RUTA { get; set; }
		public string ARCHIVO2_NOMBRE_ORIGINAL { get; set; }
		public string ARCHIVO2_NOMBRE_GENERADO { get; set; }
		public string ARCHIVO2_RUTA { get; set; }

		public string ARCHIVO3_NOMBRE_ORIGINAL { get; set; }
		public string ARCHIVO3_NOMBRE_GENERADO { get; set; }
		public string ARCHIVO3_RUTA { get; set; }

		public string ARCHIVO4_NOMBRE_ORIGINAL { get; set; }
		public string ARCHIVO4_NOMBRE_GENERADO { get; set; }
		public string ARCHIVO4_RUTA { get; set; }

		public string ARCHIVO5_NOMBRE_ORIGINAL { get; set; }
		public string ARCHIVO5_NOMBRE_GENERADO { get; set; }
		public string ARCHIVO5_RUTA { get; set; }

		public string ARCHIVO6_NOMBRE_ORIGINAL { get; set; }
		public string ARCHIVO6_NOMBRE_GENERADO { get; set; }
		public string ARCHIVO6_RUTA { get; set; }

		public string DIRECCION_CLIENTE { get; set; }

		public string CODIGO_SERVICIO { get; set; }
		public string DESCRIPCION_SERVICIO { get; set; }

        public string TRA_NUM_GR_REMITENTE1 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE1 { get; set; }
        public string TRA_PLACA1 { get; set; }
        public string TRA_BREVETE1 { get; set; }
        public string TRA_DIRECCION_INICIO1 { get; set; }
        public string TRA_DIRECCION_LLEGADA1 { get; set; }
        public string TRA_TIPO_CARGA1 { get; set; }
        public string TRA_NUM_CONTENEDOR1 { get; set; }
        public string TRA_PESO1 { get; set; }
        public string TRA_FECHA_SERVICIO1 { get; set; }
        public string TRA_TIPO_BULTO1 { get; set; }
        public string TRA_NUM_BULTO1 { get; set; }
        public string TRA_NUM_GR_REMITENTE2 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE2 { get; set; }
        public string TRA_PLACA2 { get; set; }
        public string TRA_BREVETE2 { get; set; }
        public string TRA_DIRECCION_INICIO2 { get; set; }
        public string TRA_DIRECCION_LLEGADA2 { get; set; }
        public string TRA_TIPO_CARGA2 { get; set; }
        public string TRA_NUM_CONTENEDOR2 { get; set; }
        public string TRA_PESO2 { get; set; }
        public string TRA_FECHA_SERVICIO2 { get; set; }
        public string TRA_TIPO_BULTO2 { get; set; }
        public string TRA_NUM_BULTO2 { get; set; }
        public string TRA_NUM_GR_REMITENTE3 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE3 { get; set; }
        public string TRA_PLACA3 { get; set; }
        public string TRA_BREVETE3 { get; set; }
        public string TRA_DIRECCION_INICIO3 { get; set; }
        public string TRA_DIRECCION_LLEGADA3 { get; set; }
        public string TRA_TIPO_CARGA3 { get; set; }
        public string TRA_NUM_CONTENEDOR3 { get; set; }
        public string TRA_PESO3 { get; set; }
        public string TRA_FECHA_SERVICIO3 { get; set; }
        public string TRA_TIPO_BULTO3 { get; set; }
        public string TRA_NUM_BULTO3 { get; set; }
        public string TRA_NUM_GR_REMITENTE4 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE4 { get; set; }
        public string TRA_PLACA4 { get; set; }
        public string TRA_BREVETE4 { get; set; }
        public string TRA_DIRECCION_INICIO4 { get; set; }
        public string TRA_DIRECCION_LLEGADA4 { get; set; }
        public string TRA_TIPO_CARGA4 { get; set; }
        public string TRA_NUM_CONTENEDOR4 { get; set; }
        public string TRA_PESO4 { get; set; }
        public string TRA_FECHA_SERVICIO4 { get; set; }
        public string TRA_TIPO_BULTO4 { get; set; }
        public string TRA_NUM_BULTO4 { get; set; }
        public string TRA_NUM_GR_REMITENTE5 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE5 { get; set; }
        public string TRA_PLACA5 { get; set; }
        public string TRA_BREVETE5 { get; set; }
        public string TRA_DIRECCION_INICIO5 { get; set; }
        public string TRA_DIRECCION_LLEGADA5 { get; set; }
        public string TRA_TIPO_CARGA5 { get; set; }
        public string TRA_NUM_CONTENEDOR5 { get; set; }
        public string TRA_PESO5 { get; set; }
        public string TRA_FECHA_SERVICIO5 { get; set; }
        public string TRA_TIPO_BULTO5 { get; set; }
        public string TRA_NUM_BULTO5 { get; set; }
        public string TRA_NUM_GR_REMITENTE6 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE6 { get; set; }
        public string TRA_PLACA6 { get; set; }
        public string TRA_BREVETE6 { get; set; }
        public string TRA_DIRECCION_INICIO6 { get; set; }
        public string TRA_DIRECCION_LLEGADA6 { get; set; }
        public string TRA_TIPO_CARGA6 { get; set; }
        public string TRA_NUM_CONTENEDOR6 { get; set; }
        public string TRA_PESO6 { get; set; }
        public string TRA_FECHA_SERVICIO6 { get; set; }
        public string TRA_TIPO_BULTO6 { get; set; }
        public string TRA_NUM_BULTO6 { get; set; }
        public string TRA_NUM_GR_REMITENTE7 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE7 { get; set; }
        public string TRA_PLACA7 { get; set; }
        public string TRA_BREVETE7 { get; set; }
        public string TRA_DIRECCION_INICIO7 { get; set; }
        public string TRA_DIRECCION_LLEGADA7 { get; set; }
        public string TRA_TIPO_CARGA7 { get; set; }
        public string TRA_NUM_CONTENEDOR7 { get; set; }
        public string TRA_PESO7 { get; set; }
        public string TRA_FECHA_SERVICIO7 { get; set; }
        public string TRA_TIPO_BULTO7 { get; set; }
        public string TRA_NUM_BULTO7 { get; set; }
        public string TRA_NUM_GR_REMITENTE8 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE8 { get; set; }
        public string TRA_PLACA8 { get; set; }
        public string TRA_BREVETE8 { get; set; }
        public string TRA_DIRECCION_INICIO8 { get; set; }
        public string TRA_DIRECCION_LLEGADA8 { get; set; }
        public string TRA_TIPO_CARGA8 { get; set; }
        public string TRA_NUM_CONTENEDOR8 { get; set; }
        public string TRA_PESO8 { get; set; }
        public string TRA_FECHA_SERVICIO8 { get; set; }
        public string TRA_TIPO_BULTO8 { get; set; }
        public string TRA_NUM_BULTO8 { get; set; }
        public string TRA_NUM_GR_REMITENTE9 { get; set; }
        public string TRA_NUM_GR_TRANSPORTE9 { get; set; }
        public string TRA_PLACA9 { get; set; }
        public string TRA_BREVETE9 { get; set; }
        public string TRA_DIRECCION_INICIO9 { get; set; }
        public string TRA_DIRECCION_LLEGADA9 { get; set; }
        public string TRA_TIPO_CARGA9 { get; set; }
        public string TRA_NUM_CONTENEDOR9 { get; set; }
        public string TRA_PESO9 { get; set; }
        public string TRA_FECHA_SERVICIO9 { get; set; }
        public string TRA_TIPO_BULTO9 { get; set; }
        public string TRA_NUM_BULTO9 { get; set; }
        public string FLAG_TRANSPORTE1 { get; set; }
        public string FLAG_TRANSPORTE2 { get; set; }
        public string FLAG_TRANSPORTE3 { get; set; }
        public string FLAG_TRANSPORTE4 { get; set; }
        public string FLAG_TRANSPORTE5 { get; set; }
        public string FLAG_TRANSPORTE6 { get; set; }
        public string FLAG_TRANSPORTE7 { get; set; }
        public string FLAG_TRANSPORTE8 { get; set; }
        public string FLAG_TRANSPORTE9 { get; set; }
    }
}